---
title: "About"
---
## Servitude in the Colonial Period
    - The experiences of enslaved individuals varied by gender

### Indentured Servitude
- The first indentured servants arrived to Virginia in 1624
- It was typical for indentured servants to be bound for three to five years after their arrival in the colonies
- Many times, someone would agree to an indenture contract because they could not afford the cost of transportation to the Americas
    - Some people were "spirited" or kidnapped to be taken to the New World and sold into servitude (Snyder) 

### Enslavement 
-
-
-

### Labor
- At the beginning of the colonial period, labor was typically unskilled with a shift to skilled labor happening with the introduction of staple crops.
- Tasks of skilled laborers might include building storage sheds, packing products, and transporting products.
- As operations grew, white skilled laborers shifted their roles to working as overseerers and managers.
- The two most requested skills for laborers in the 1640s were construction and carpentry. (Galenson) 


### Isolation
- Enslaved and Indentured Black women were heavily isolated in the colonial period.
  - The disperal of homesteads led to the disperal of people
- Black women had little connection to their culture or community (Gunderson)
