---
title: "White Women's Roles and Expectations"
---
### Married Women 
- Women's roles in their homes depended on the supplies they could afford
- Women were largely reponsible for all the things that happened inside the home
- Duties might include caring for children, making and mending clothing, cooking, cleaning, garden, preserve foods, and more
- The duty to bear children was perhaps regarded as the most important of the time period
  - Women were expected to be fruitful and populate the Earth, as per Biblical teaching



### Unmarried Women
- Unmarried Women had slightly different roles
- Their main expectation was to provide for themselves through some form of work
- During the colonial period, jobs were much less split up by gender
  - Women often worked jobs that would later be reserved for men, like blacksmiths
- Women would very quickly become experts in their fields (Treckel)  


### Public and Private Life 
- In the early colonial period, wealthy women were allowed to exist within the public sphere, but this changed in the later colonial period. 
  - Women were expected to stay within private life and not enter into public spheres.
  - The public sphere was seen as a man's world.
  - After 1700, a woman's value was found in their femininity, not in their political status.
  - Some women made their own methods of participating in the public sphere.
    - Some women made charity organizations or participated in church activities and groups. (Norton) 
