---
title: "Servitude in the Colonial Period"
---

### Indentured Servitude
- The first indentured servants arrived to Virginia in 1624
- It was typical for indentured servants to be bound for three to five years after their arrival in the colonies
- Many times, someone would agree to an indenture contract because they could not afford the cost of transportation to the Americas
    - Some people were "spirited" or kidnapped to be taken to the New World and sold into servitude (Snyder) 

### Shift to Enslaved Laborers
- As indentured servitude became more financially burdensome in the colonies, farmers turned to enslaved labor. 
- This switch might be due to the switch from subsistance to staple crop farming. 
- With a higher demand for staple crops, there was a higher demand for skilled labor. 
- As operations grew, white laborer's roles changed from doing labor work to working as overseerers and plantation managers.
- As time went on, enslaved laborers born in the colonies became less expensive to traffic and train. (Galenson)

### Enslavement 
- Enslaved laborers roles differed by plantation. 
- Skilled and unskilled laborers were required to run a plantation. 
- Enslaved workers were trafficked and purchased, and had no opportunities to become free except for manumision. 


### Labor
- At the beginning of the colonial period, labor was typically unskilled with a shift to skilled labor happening with the introduction of staple crops.
- Tasks of skilled laborers might include building storage sheds, packing products, and transporting products.
- As operations grew, white skilled laborers shifted their roles to working as overseerers and managers.
- The two most requested skills for laborers in the 1640s were construction and carpentry. (Galenson) 


### Isolation
- Enslaved and Indentured Black women were heavily isolated in the colonial period.
  - The disperal of homesteads led to the disperal of people
- Black women had little connection to their culture or community (Gunderson)
