---
title: "Sources"
editor: visual
---

Galenson, David W. “White Servitude and the Growth of Black Slavery in Colonial America.” The Journal of Economic History 41, no. 1 (1981): 39–47. [http://www.jstor.org/stable/2120891.](http://www.jstor.org/stable/2120891.(Article))

Gundersen, Joan Rezner. “The Double Bonds of Race and Sex: Black and White Women in a Colonial Virginia Parish.” *The Journal of Southern History* 52, no. 3 (1986): 351–72. https://doi.org/10.2307/2209567.

Kirkman, Alyssa. *The Meeting of Mothers, Midwives, and Men.* Harding University, 2013.

Norton, Mary Beth. *Separated by their sex: Women in public and private in the colonial Atlantic World*. Ithaca, NY: Cornell University Press, 2014.

“Smith Island Historical Marker.” Historical Marker, August 22, 2022. https://www.hmdb.org/m.asp?m=8285.

Snyder, Mark R. “The Education of Indentured Servants in Colonial America.” *The Journal of Technology Studies* 33, no. 2 (2007): 65–72. http://www.jstor.org/stable/43604120.

Sutherland, Stella H. (1975). ["Chapter Z: Colonial and Pre-Federal Statistics (Series Z 1-19: Estimated Population of American Colonies: 1610 to 1780)"](https://www2.census.gov/library/publications/1975/compendia/hist_stats_colonial-1970/hist_stats_colonial-1970p2-chZ.pdf) (PDF). *Bicentennial Edition: Historical Statistics of the United States, Colonial Times to 1970, Part 2*. Washington, D.C.: [U.S. Census Bureau](https://en.wikipedia.org/wiki/U.S._Census_Bureau "U.S. Census Bureau"). p. 1168.

Treckel, Paula A. *To comfort the heart women in Seventeenth-century America*. New York, NY: Twayne Publishers, 1996.

Wawrzyczek, Irmina. “The Women of Accomack versus Henry Smith: Gender, Legal Recourse, and the Social Order in Seventeenth-Century Virginia.” *The Virginia Magazine of History and Biography* 105, no. 1 (1997): 5–26. http://www.jstor.org/stable/4249614.
